module.exports = {
  race: { type: String, default: "" },
  origin: { type: String, default: "" },
  enhancingAscension1: Number,
  modifingAscension1: Number,
  origin2: { type: String, default: "" },
  enhancingAscension2: Number,
  modifingAscension2: Number,
  lifeDie: { type: Number, default: 0 },
  class: { type: String, default: "" },
  class2: { type: String, default: "" },
  defensiveSpecialty: { type: String, default: "" },
  ofensiveSpecialty: { type: String, default: "" },
  past: { type: String, default: "" },
  personality: { type: String, default: "" },
  occupation: { type: String, default: "" },
  goal: { type: String, default: "" },
  flaw: { type: String, default: "" },
  firstAlignment: { type: String, default: "" },
  secondAlignment: { type: String, default: "" },
  name: { type: String, default: "" },
  avatar: String,
  feats: [String],
};
